### ISSUE TITLE
Fuzzy linkage is handled as illegal structure in WURCS exporter.

### ISSUE THREAD

**Issue by e15d5605** [glycoinfo/GlycanBuilder2#2]
When encode WURCS string from glycan containing branch of fuzzy linkage, these linkages are handed as illegal structure.  When verifying the linkage position of monosaccharide with a branch, these fuzzy state can not be determined.  For example, if these monosaccharide are attached to the acceptor side at 3 or 4, these position are recognized as 3.<br>

<img width="135" alt="スクリーンショット 2019-12-12 9 23 17" src="https://user-images.githubusercontent.com/15099705/70671947-2009cb00-1cc1-11ea-8fb8-3c0d3f373b77.png">

Error code
```
java.lang.Exception: This glycan have illegal linkage posiiton
	at org.glycoinfo.application.glycanbuilder.util.exchange.GlycanToWURCSGraph.start(GlycanToWURCSGraph.java:33)
	at org.glycoinfo.application.glycanbuilder.converterWURCS2.WURCS2Parser.writeGlycan(WURCS2Parser.java:22)
	at org.eurocarbdb.application.glycanbuilder.GlycanDocument.toString(GlycanDocument.java:1451)
	at org.eurocarbdb.application.glycanbuilder.GlycanDocument.toString(GlycanDocument.java:1430)
	at org.eurocarbdb.application.glycanbuilder.GlycanDocument.exportFromStructure(GlycanDocument.java:1279)
	at org.eurocarbdb.application.glycanbuilder.GlycanCanvas.onGetStringFromStructure(GlycanCanvas.java:3560)
	at org.eurocarbdb.application.glycanbuilder.GlycanCanvas.actionPerformed(GlycanCanvas.java:4080)
	at org.eurocarbdb.application.glycanbuilder.GlycanAction.actionPerformed(GlycanAction.java:230)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6636)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6401)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2762)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**Comment by e15d5605** [comment]
This problem is already resolved (20200106 committed).
