### ISSUE TITLE
Problem exporting GlycoCT for structures containing phosphate bridges

### ISSUE THREAD

**Issue by kate1711** [glycoinfo/GlycanBuilder2#27]
Hi 
I have a structure with two internal phosphate bridges, I can draw them in GlycanBuilder2 (which is great). However, when I try to export the structure to GlycoCT format, it throws an error. How can i overcome this?
Regards
Catherine

**Comment by yamadaissaku** [comment]
Reproduced and diagnosed against 1.31.0.

**Reproduction** — any structure with a phosphodiester bridge; the smallest is

```
WURCS=2.0/2,2,1/[a2122h-1b_1-5][a2112h-1b_1-5]/1-2/a6-b1*OPO*/3O/3=O
```

Import succeeds, and GlycoCT export returns an **empty string** — the "error" seen in the desktop dialog is this failure surfaced; through `GlycanDocument.toString("glycoct_condensed")` it is silent.

**What actually fails** — the exporter throws internally and the exception is swallowed:

```
GlycoVisitorException: Unknown residue (aglyca?): ?-P
  at GlycoVisitorToGlycoCT.visit(GlycoVisitorToGlycoCT.java:433)
  ...
  at GlycoCTParser.toSugar(GlycoCTParser.java:228)
```

**Cause chain**

1. The bridge residue `P` (superclass `Bridge`, IUPAC name `P`) is not treated as a substituent by `GlycoCTParser.getIupacName`, so it takes the *saccharide* branch, which prepends the anomeric state: the node handed to MolecularFramework is named **`?-P`**.
2. Even without the prefix, `P` is not a GlycoCT substituent name. A phosphodiester bridge in GlycoCT is the substituent **`phosphate`** with two linkage edges — so the fix needs a mapping from the cross-linked-substituent types to their GlycoCT names (P → phosphate, and the same question for PPEtn and the other bridges), not just a branch correction.
3. The exception is caught and turned into an empty result, which is why the desktop writes an empty file rather than saying what happened.

Fix planned for a following batch: name bridges by their GlycoCT substituent vocabulary in the exporter (and say *something* when export fails, rather than emitting nothing). Related family: #45 fixed the substituent attach positions in 1.31.0; this is the remaining bridge half.

**Comment by yamadaissaku** [comment]
Fixed on `develop` (PR #139), scheduled for the next release. The reported case — a phosphodiester bridge — now exports

```
RES
1b:b-dglc-HEX-1:5
2s:phosphate
3b:b-dgal-HEX-1:5
LIN
1:1o(6+1)2n
2:2n(1+1)3o
```

and round-trips through the GlycoCT reader. The same holds for the S, SH, N, Suc and PyrP bridges. Three bridges remain unexported by design for now — NS, PEtn and PPEtn attach through two *different* atoms (N on one side, S/O on the other), and the model does not record which sugar got which side, so exporting them would mean guessing a linkage type; they still produce the old empty result. If those matter to your structures, please say so here and we will look at carrying the attachment orientation through the model.
