### ISSUE TITLE
Migrate dependency from Log4j 1.x to Log4j 2.x.

### ISSUE THREAD

**Issue by e15d5605** [glycoinfo/GlycanBuilder2#33]
![image](https://user-images.githubusercontent.com/15099705/146698311-347335e0-3c02-4663-bc3f-03a563cc4487.png)

参考サイト：https://www.toyfish.blog/entry/20121213/p1

Log4jの更新によってログ取得の実装にどのような違いが生じているのかを確認する必要がある\
動作確認などの作業も考慮してLog4j用の専用のブランチを作成して作業を行う

**Comment by e15d5605** [comment]
GlycanBuilder2ではlog4jの1.2.17を使用しており、1.x系のサポートが終了しているため現行版の2.x系に移行する必要がある\
log4jの2.x系に関しては、2021年の12月17日に脆弱性に対応したバージョンが公開されるなど、安定性に欠ける要素も見られるとのこと（[参考](https://japan.zdnet.com/article/35181084/)）\
脆弱性を解決したバージョンとして`log4j-api`というものも公開されているため、どの環境を導入するのかを検討する必要がある（参考：[log4j-apiを利用したソフトウェア](https://github.com/cdk/cdk/commit/e05f6f1a21737d02ab24d5e2a874d6383da6eb36)）\

**Comment by MasaakiMatsubara** [comment]
log4jの`1.x`系の関係者は、SLF4J/logbackに移行することを推奨しているようです。
http://slf4j.org/log4shell.html

参考：https://piyolog.hatenadiary.jp/entry/2021/12/13/045541
記事内、「1.x系への影響」より

log4jとslf4jは、コードの互換性の問題がありますが、`2.x`系で言うところの`log4j12-api`として、`slf4j-log4j12`や`log4j-over-slf4j`などが用意されているので、それを使えばその問題は解消できるみたいです。
どちらがいいかですが、元々コードでslf4jを使っていないのであれば、`log4j-over-slf4j`を使う方がいいみたいです。
参考：https://stackoverflow.com/questions/31044619/difference-between-slf4j-log4j12-and-log4j-over-slf4j/31044844

参考まで。

**Comment by e15d5605** [comment]
@MasaakiMatsubara 情報を共有していただきありがとうございます。`slf4j`は把握しておりませんでしたので確認いたします。

**Comment by e15d5605** [comment]
### log4j 1.x系を使用しているソフトウェア

* GlycanBuilder2
  * 1.2.17
  * https://github.com/glycoinfo/GlycanBuilder2
* GlycoWorkbench (maven)
  * 1.2.17
  * https://github.com/e15d5605/glycoworkbench
* GlycanBuilderVaadin7 version
  * 1.2.12
  * https://github.com/e15d5605/GlycanBuilderVaadin7Version
    * https://github.com/e15d5605/GlycanBuilderVaadin7Version/tree/master/glycanbuilderv/WebContent/WEB-INF/lib  
* GlycoWorkbench (stand-alone)
  * 1.2.12
  *

**Comment by e15d5605** [comment]
調査の一環としてGlycanBuilder2のLoggerの環境設定を確認していた、以下のように設定されている

```
log4j.rootCategory=DEBUG, Appender1
log4j.appender.Appender1=org.apache.log4j.FileAppender
log4j.appender.Appender1.File=/srv/www/tomcat_production/MsdbWeb/hibernate.log
log4j.appender.Appender1.layout=org.apache.log4j.PatternLayout
log4j.appender.Appender1.layout.ConversionPattern=%d{yyyy/MM/dd HH:mm:ss.SSS} [%t] %-6p %m%n
```

参照するログファイルの階層が以下のように設定されており、ローカルでGlycanBuilder2を実行した際に参照エラーが出力される
```
log4j.appender.Appender1.File=/srv/www/tomcat_production/MsdbWeb/hibernate.log
```

```
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /srv/www/tomcat_production/MsdbWeb/hibernate.log (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:292)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:156)
	at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
	at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
	at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:307)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:172)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:104)
	at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:842)
	at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
	at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:648)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:514)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:580)
	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
	at org.apache.log4j.Logger.getLogger(Logger.java:117)
	at org.eurocarbdb.application.glycanbuilder.ThemeManager.<clinit>(ThemeManager.java:20)
	at org.eurocarbdb.application.glycanbuilder.GlycanBuilder.<init>(GlycanBuilder.java:93)
	at org.eurocarbdb.application.glycanbuilder.GlycanBuilder.main(GlycanBuilder.java:889)
```

GlycanBuilder2を実行した際に毎回エラーが出ていたが、論文の公開が近かったこともあり応急処置として起動時にLoggerを参照している箇所をコメントアウトしていた\
コメントアウトの対象は以下のクラス

* BookingManager
* ICON_PATH
* ThemeManager

`/srv/www/tomcat_production/MsdbWeb/hibernate.log`がどのような目的で設定されたのかを調べる必要がありそう

**Comment by MasaakiMatsubara** [comment]
GB3でロギングの仕組みを一新する予定のため対応は不要、解決としクローズする
