### ISSUE TITLE
A closed-loop is composed in repeating unit. 

### ISSUE THREAD

**Issue by e15d5605** [glycoinfo/GlycanBuilder2#54]
繰り返し構造のWURCSを読み込んだ際に生成されるGlycanを描画機能や質量計算機能で処理する際にStackOverFlowを返している。
この原因を調査し、問題のある機能を修正する。

**Comment by e15d5605** [comment]
wurcs2image APIでNアセチルノイラミン酸の繰り返し構造を描画した際に、画像が返されていないという報告を受けた。

https://api.glycosmos.org/wurcs2image/latest/png/binary/G39122DY

このAPIはGlycanBuilder2を利用しているため、v1.18.1のGlycanBuilder2で同様のWURCSを読み込んだ。結果として以下のようなエラーメッセージが出力され、最終的にStackOverFlowが発生して処理を強制終了していた。
```
at org.eurocarbdb.application.glycanbuilder.util.TextUtils.tokenize(TextUtils.java:184)
	at org.eurocarbdb.application.glycanbuilder.ResidueType.getMinRepetitions(ResidueType.java:468)
	at org.eurocarbdb.application.glycanbuilder.converterGWS.GWSParser.writeResidueType(GWSParser.java:202)
	at org.eurocarbdb.application.glycanbuilder.converterGWS.GWSParser.writeSubtree(GWSParser.java:236)
	at org.eurocarbdb.application.glycanbuilder.converterGWS.GWSParser.writeSubtree(GWSParser.java:284)
	at org.eurocarbdb.application.glycanbuilder.converterGWS.GWSParser.writeSubtree(GWSParser.java:259)

       * これ以降はGWSParser.java:284とGWSParser.java:259の処理を無限に繰り返しているため割愛
```

GWSParserの該当箇所を確認すると、以下のような処理だった。

- GWSParser.java:284
```
	static public String writeSubtree(Linkage l, boolean ordered, BBoxManager bboxManager) {
		return ("--" + toStringLinkage(l) + writeSubtree(l.getChildResidue(),ordered,bboxManager));
	}
```

- GWSParser.java:259
```
		for( Linkage l : r.getChildrenLinkages() )
			str_children.add(writeSubtree(l,ordered, bboxManager));
```

rというResidueから子ノードを参照し、writeSubtreeという関数で子情報のGWSを追記するという処理で問題が発生していた。この関数ではResidueから子ノードを参照することで、再帰的に全ての単糖の情報を描画している。これらの処理が無限に続くことから、本来は単糖の子ノードを参照して糖鎖の葉側に進むはずの処理が、何らかの原因で根側に戻ってしまっているため無限に繰り返されていると考えられる。このことから、繰り返し構造のWURCSから生成されたGlycanのResidueの親子関係を調査した。

**Comment by e15d5605** [comment]
エラー報告で提示されていた糖鎖構造のWURCSからGlycanを生成し、全ての単糖の親子関係を確認した。
```
WURCS=2.0/1,1,1/[Aad21122h-2a_2-6_5*NCC/3=O_7%?%*OCC/3=O_8%?%*OCC/3=O]/1/a2-a9~n
```

Glycanの繰り返し構造はStartRep-Monosaccharide-...-EndRepで構成される。単糖だけでなく繰り返し構造のブラケットも糖鎖を構成する要素として扱っているため、ブラケットと単糖間の親子関係も形成する必要がある。今回のケースでは、（親）StartRep-（子）Nアセチルノイラミン酸、（親）Nアセチルノイラミン酸-（子）EndRepの親子関係を形成することで、単糖の繰り返し構造を描画することが可能になる。

しかしながら、末端のEndRepの親子関係を確認すると、（親）EndRep-（子）Nアセチルノイラミン酸になっており、本来の親子関係と逆転していることを確認した。これにより、（親/子）Nアセチルノイラミン酸-（子/親）EndRepとなってしまい、子情報を永久に参照し続けられる構造になっていることが判明した。

**Comment by e15d5605** [comment]
TODO: 繰り返しの親子が無限ループになる箇所を特定して整理する

- GLIN2Linkage::setGRESs
```
if(!_gres.getAcceptorGLINs().isEmpty()) {
			LinkedList<GLIN> a_aGLINs = _gres.getAcceptorGLINs();
			if(a_aGLINs.getFirst().getDonor().contains(_gres)) {
				this.acceptorGRESs.addAll(a_aGLINs.getFirst().getDonor());
			...
```

- LinkageConnector::analyzeBracketNotation
```
else if(a_oRES.getStartCyclicResidue() == null && !a_oG2L.getParents().isEmpty()){
			Residue a_oParent = this.acceptor;
			if(this.isOutRepeating(a_oRES, a_oParent)) {
				// end repeating bracket to monosaccharide : o<->[-o
				a_oParent.getEndRepitionResidue().addChild(a_oRES, a_oRES.getParentLinkage().getBonds());
                      ...
```

WURCSSequence2の解析処理で参照されるGLIN2Linkageで、親ノードを正しく参照できていない疑いがある。WURCS2からGlycanを生成する処理では、GRES2ResidueでGRESからResidueへ変換し、GLIN2LinkageでLinkageへの変換を行う。この段階では、Glycanを構成するResidueはバラバラの状態である。LinkageConnectorはこれらのバラバラに分断された糖鎖の部品を、GLIN2Linkageで定義した親子関係を参照しながら繋ぐ。しかし、GLIN2LいんかげでGLINを解析した時に定義された親子関係に誤りがあり、以下のように解釈されたと考えられる。

- 正しい親子関係
```
StartRep->Nアセチルノイラミン酸->EndRep
```

- 誤った親子関係
```
StartRep->Nアセチルノイラミン酸->EndRep→Nアセチルノイラミン酸（EndRepの親と同様）

StartRep->Nアセチルノイラミン酸<->EndRep
```

繰り返し構造は特定の単糖のグループが繰り返し見られる糖鎖構造であり、繰り返しの開始点と終点は親子関係を持つ。そのため、単一の単糖で構成された繰り返し構造の場合は、その単糖の親と子に自分自身を持つということになる。GLIN2Linkageでこのような条件を適切に処理できていないため、クリア返しの終点に位置するNアセチルノイラミン酸が、子を持つ単糖として判断されたと考えられる。また、その子ノードは繰り返しの外の単糖として判断されたため、EndRep->Nアセチルノイラミン酸の親子関係が定義された。

**Comment by e15d5605** [comment]
GLIN2Linkageで繰り返し構造内の単糖の親子関係を確認する際に、以下の条件を考慮する。
1. 単一の単糖の繰り返し構造の場合、親子が自分自身ではないか
2. 複数の単糖の繰り返し構造の場合、親が開始単糖でないのか

自分自身が繰り返し構造の一員なのか、親子のノードが自分と同じ繰り返し構造に所属するものかを確認すると良さそう。

TODO: LinkageConnectorの修正が必要か検討

**Comment by e15d5605** [comment]
GLINToLinkageには`analyzeAcceptorGLIN`と`analyzeDonorGLIN`という関数が実装されている。これらの関数では繰り返し構造の解析を行っており、以下のような名称の関数を参照している。

- GLINToLinkage::analyzeAcceptorGLIN
  - if(a_oAGLIN.isRepeat()) this.analyzeRepeatingGLINforChild(a_oAGLIN);
- GLINToLinkage::analyzeDonorGLIN
  - if(a_oDGLIN.isRepeat()) this.analyzeRepeatingGLINforParent(a_oDGLIN);

これらは、繰り返し構造の開始点・終点の単糖のGLINを解析して結合位置を取り出すための関数である。`analyzeRepeatingGLINforChild`では、StartMonosaccharide-StartRepの間の結合位置を取り出しをした後に、繰り返し構造のStartMonosaccharideを参照している。一方で、`this.analyzeRepeatingGLINforParent(a_oDGLIN);`では、EndRep-EndMonosaccharideの結合位置を取り出している。

前者の処理を確認したところ、単一の単糖の繰り返し構造では自分自身を別の親子として判断してしまったことや、繰り返しの開始単糖と終点単糖の親子関係を参照方法が間違っていた。本来は開始地点->終了地点と定義されているものが、終了地点→開始地点で前後関係を参照していた。これにより、繰り返し構造の開始地点と終了地点が入れ替わっていた。

以上のことから、GLINの繰り返し構造の解析時に以下のような条件で対応する必要がある
1. 単糖の繰り返し構造の前後関係を参照した時にGRESのIDが重複していないか
2. 複数の単糖の繰り返し構造の前後関係を参照した時にGRESのIDが若い方が開始単糖になっているか

さらに、analyzeRepeatingGLINforChildの開始単糖を参照する処理を以下のように書き換える。

誤り
```
this.startGRES = _acceptorGLIN.getDonor().get(0);
```

改定案
```
this.startGRES = _acceptorGLIN.getAcceptor().get(0);
```

**Comment by e15d5605** [comment]
繰り返し構造で無限ループになる結合が形成されていた原因は、WURCSSequence2の解析処理で繰り返し構造を構成する親子の単糖の参照方法に問題があるためだった。この問題の解決手段として、単独の単糖の繰り返し構造から親・子の単糖を参照しない方法を考えられる。しかし、これらは後のLinkageConnectorで必要な要素である。今回の問題は繰り返し構造を構成する単糖と子ノードとの結合を定義する処理で発生している。そこで、LinkageConnectorで繰り返し構造の単糖の結合を確認する時に、親子が同じ単糖であるかを確認するようにした。

- LinkageConnector::analyzeBracketNotation
```
private void analyzeBracketNotation (Residue a_oRES, Residue a_oBridge, GLINToLinkage a_oG2L) {
    * 繰り返しのブラケットと単糖の結合を定義する処理
    ...
    // for repetition contains single monosaccharide
    if (this.donor.equals(this.acceptor)) return; <-新しく追加した処理
    
    // make glycosidic linkage for outside of repetition
    if(a_oRES.getStartRepetitionResidue() != null && a_oRES.getStartCyclicResidue() == null && a_oG2L.getAcceptorGLINs().size() > 1) {
    * 以下、繰り返し構造の前後と単糖の結合を定義する処理
```

この状態で描画時に無限ループが発生していたWURCSを入力した
```
WURCS=2.0/1,1,1/[Aad21122h-2a_2-6_5*NCC/3=O_7%?%*OCC/3=O_8%?%*OCC/3=O]/1/a2-a9~n
```
<img width="258" alt="image" src="https://user-images.githubusercontent.com/15099705/187817540-72828037-e9a5-41fd-820a-575b503f9a0b.png">

**Comment by e15d5605** [comment]
無限ループと直接関している内容では無いが、繰り返し構造のGLINを解析する際にDonor/Acceptorの向きが異なることを確認した。
置換基を挟む場合と、そうでない場合とで開始単糖/終了単糖の参照方法が異なっている。これに気がつかないまま両方の繰り返し構造を解析していたため、正しく糖鎖構造を描画することができなくなっていたと考えられる。

この問題を解決するために、繰り返し構造のAcceptor/Donor GLINが保持しているGRESのIDを確認し、繰り返し構造の開始単糖/終了単糖を定義するようにした。従来の使用では、AcceptorGLINの繰り返し構造をEndRep、DonorGLINの繰り返し構造をStartRepと固定して対応していたが、今回のようにGRESのIDで判断することで柔軟に対応することが可能となる。

**Comment by e15d5605** [comment]
検証用繰り返し構造のWURCS

```
WURCS=2.0/1,4,4/[a2122h-1a_1-5]/1-1-1-1/a4-b1_b4-c1_c4-d1_a1-d4~n
```

**Comment by e15d5605** [comment]
## ImageMagickを用いた画像比較
```
compare -metric AE <Image A> <Image B> NULL: ;
```

- 画像が同じ
  > ![latest](https://user-images.githubusercontent.com/15099705/202655776-f9d07c38-d2e6-4f26-bfdd-81fe51073598.png)
  > ![0 8 0](https://user-images.githubusercontent.com/15099705/202655784-d8b454a3-aeac-4565-b568-d9cb9250a842.png)
  > 比較結果：0
- 画像が異なる
  > ![latest](https://user-images.githubusercontent.com/15099705/202655923-a18898ce-c179-4de9-8f05-8ac7e43fc60a.png)
  > ![0 8 0_L](https://user-images.githubusercontent.com/15099705/202655944-18fcae65-46ae-41e4-ae42-6da544b5b600.png)
  > 11

完全一致する場合は0が出力され、一致しなかった場合はそれ以外の数字が出力される。バージョン変更前後のWURCS2Picを使用して糖鎖構造のイメージを生成し、ImageMagicで比較する。0以外の戻り値が得られた場合は、バージョンの違いでイメージに何かしらの変更が見られた糖鎖構造として確認する。

**Comment by yamadaissaku** [comment]
ImageMagickを用いた画像比較は、どのように行われているのかわかりますか？

**Comment by e15d5605** [comment]
@yamadaissaku 詳しいアルゴリズムに関しては、調べきれていないのでお答えできないです。上のサンプルで示した比較は`-metric AE`というオプションを利用しています。これは、画像間のピクセル単位のズレを比較するというオプションです。他にも多くの比較用オプションが実装されていることを確認しています。参考までに、ここにImageMagickの[オプションを記載したドキュメント](http://www.imagemagick.org/script/command-line-options.php#metric)を共有させていただきます。

**Comment by MasaakiMatsubara** [comment]
GlycanTranslatorとGlycanCoreで対応済みのため、クローズする。
ImageMagikによる画像比較方法は共有する。
